spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
mybatis-plus:
  type-aliases-package: com.lxg.mapper
  global-config:
    id-type: 0
    db-column-underline: true